// GENERATED by scripts/optimize-media.mjs — do not edit by hand.
// Tiny blur placeholders (16px WebP, base64) keyed by public path.
export const blurData: Record<string, string> = {
  "/media/night/DSC00089-HDR.webp": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAA4BaJbACdAD0p13Z/VPkAAD+9rQlwQmQXffOvw9lZ9D3tLd1i1SMlo2pYd734Lj6N0EiHYYkPlJdSwc0SnEtsIMREd1iHnQumBn2tq8yNh9LyxWveUOOjXL48u2VhGMqCcAAAA==",
  "/media/night/DSC00092-HDR.webp": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQAgCdASoQAAsAA4BaJbACdEf/i13N6rTLswAA/vXA0xCo9UOimtWM7rbAmaEqjpanIm9bRYs92MV8yOaZq8aXV9+DsFj7x4qWL1HwAQ2fWufMzjtxNNmcsFHuyTJED4tGvgV2+GG5rfiTXl1uXAAA",
  "/media/night/DSC00095-HDR.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoQAAsAA4BaJbACdAEO6sLJsfygAAD+8SPVqNwsVnycVVeXLDZ+N4Cy/pk+3+mZMprPqartqpvGtwpc95eDISkFip/TdxGDqvgqA7P+MLEMaDbXq95UvdPiuBITbNVKkYkqYEAA",
  "/media/night/DSC00098-HDR-Pano-2.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAgAA4BaJbACdAEO5b8mgQ8AAP7zVQw8C4eL/VdQo+brMJFPJJNIoFTX8kwRLHn8qJrdXwAxJnVev+wIWfih6EFoCGulcgfObAAA",
  "/media/night/DSC00098-HDR-Pano.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAgAA4BaJbACdAYtzvukyI2I8AD+8YbdUXrQWBv+EzaOIfInAkyuygNrhaau7MDOk5Szvyb8pYJ4qvyVLUGhdT/cE8ZC924kD3+nhRxVeEjt17wAAA==",
  "/media/night/DSC00098-HDR.webp": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA4BaJbACdAYwdypjiUIAAP7sW+ok2TTEFWcTs538imx9b7/G5s76BibBvX2AFIjdJ3Gr0EIsGTT87goWj4uw7M2aHJw1fNhKOmaJYcVgUBlsiYlz6yz3pG4CZHL7rSDOAAA=",
  "/media/night/DSC00104-HDR.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoQAAsAA4BaJbACdH8AFd54Jf6yAAD+9rRWymthS0GnNtiFDmn7gqdRjKuxcUJMULRDQM7SvZRNbopHQDnST1RT/YjecO9czR2KHx5G2iSRmoihUZ/riO5Hd+nMeGE5pvoV/rgA",
  "/media/night/DSC00110-HDR.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJbACdAEO6sT29zyIAP7xI6gjb0jK+82GF3VTlmJRezjcW8VET9Bb3jS+f9+KpbBRGG6eA57WPwtk+RgPO/VsvX09bexle5SpFNXBW2e/cqnx3pCiMZAA",
  "/media/night/DSC00116-HDR.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAsAA4BaJbACdAEVV8G7Qv2DAAD+6V/n2bNKcdQ352V+wXgN8qScgciHXAAzE5TP5Hqo1ggaS4xXrBfUdezUoWUTACeS7cCI84RFgWVMYJje+z4frrMi9VnuBuQA",
  "/media/night/DSC00146-HDR-2.webp": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbAC7AB6VEh88sfALcRIWAAD+8y/m2ahZG+Swtv2CMGEZSfOSptTUwR4IcPmczqJMa0W2dhTGv0MfgTeQ04bkL2vf/RBLblW7T4olbitxyzGlrecmospGsNwVitidvkw+p1wS82+o77SLLOikYVfzxAAAAA==",
  "/media/night/DSC00146-HDR.webp": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoQABgAPu1iqk4ppaQiMAgBMB2JZgAAUrS+oe1dvqbvj2kwAP7zL+bZqFkb5LC3KiBu8khc5KmgJpUcix4o2vPjmh9Fir2KcqoqIZwZBulj2V73rMxFStaHgmghT378pxXTjfMC6ciFbxXNCmy6JxX/U5M5izG9ZJoCh4MpgAA=",
  "/media/night/DSC00149-HDR.webp": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABwBACdASoQABgAPu1kqk4ppaQiMAgBMB2JQBhQMXhb7M5nRWf1jU907fkIAAD+9CqEtfYQGL9yRuHHwOAvI0DEme7DPl8SokTSr0MLxtYsDUAnWuUQ7RNHsGDcicBxUwLJFpAfKjdIN9TFgedFpg4JH/dgwfPcTVYmPPjNiaXy8AAA",
  "/media/night/DSC00152-HDR.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAsAA4BaJZgC7AC5K73BQAD++I23r+X3krZXRk+S1XHzYRVPn7CtfrMqg4Y1NpjlKArnbFFrA5hA1OA+HUsoH+lW18EIp+3Ts3foVrmd8EcHC2YAAA==",
  "/media/night/DSC00170-HDR.webp": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JagCdL1yVek7f+ca46BrGCFDOUAD+8yXBy4LEFFGkqyFzEC0yFIntkAxHbzBDA03xaxenA6fQqWFcWAjUcrLo3L/RXNc4SmrZgoXOb5+HCZKp+RG/aMt5fdfkSgoIurrzT5G8gKN7b0TX/W36CgAA",
  "/media/night/DSC00173-HDR.webp": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAA4BaJZgCdAYv1q/SgK1kj4AA/vGjPGBr55lobWDo3o3Mgi+4wxBul9NTbNhoOKyRCs7a1eumf+CV6mx0NVQLmxJC6x2CGlVLyg6HovBcs0f6Ac0eCKIAAA==",
  "/media/night/DSC00176-HDR.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAgCdASoQAAsAA4BaJbACdAYrx2Vz6mdZzPkIAP7xlkOe404mOtAIzlNNFaVsR90OJOrI+eps1SWcFJMK1dKXlrmnd8yhtazZYYXeV1HMKNm+yDIuDmpHalFgp6MOn5Un0AAA",
  "/media/night/DSC00179-HDR.webp": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwAgCdASoQAAsAA4BaJbACdEf/i19aiNWA0AD+3h8qZX5Zv9KqaNQ7HpzUwu5CKUHglyJ8jP5APilmPP19uK65V6dy8h7lPN9yCW2iFd6jbL4Ar4lZyN+bTaYeFnyvXTYU8xDLtQpkbxVHqSYqyKDT5UC1ZBiGAqAAAA==",
  "/media/night/DSC00182-HDR.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJbACdAEKmNk2DV6AAP70OOaPouckdKYPiBE91YKeAqGqrS7ia+kEGXGP9FCe/5juZJNuiRZQqfsUzQa5KSaU/qxPLozcQAA=",
  "/media/night/DSC00185-HDR.webp": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAsAA4BaJbACdADDtT+V/PIAAP7vgdJxrAy8qVGJpQsrPb8jNabvqO/RQbyicoYF9798G09NNJDW8a76IaXzQvvJL4DG3h/zW1tiwnUJtwmoGbfkyvNnxfktv1ybKAAAAA==",
  "/media/night/DSC00188-2-HDR.webp": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwAgCdASoQAAsAA4BaJbACdAYv/zSZ9G2B9AD+h++38embr8mZBFkkoIVQDw+00z168ZT0e4jNLjsIuFW9hAgoV8TUCQhK0bV+EHGfr+Gk9gYgHIVEn0Bcts0gswh+L95SgAojrP0+skKJORTMmGy98mHAAA==",
  "/media/night/DSC00191-HDR.webp": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAQCdASoQAAsAA4BaJbACdADdLU/C+dAA/q0NCskz7gJV1xU7JUgv6Jt4A6T9znN4GKQCzkRuW8ux0j7rftZhosx4ffkydV5m02guZhKoj4c2N+m4HtC4r2QdHc5FVPczEr27a54lMvw3cWcxL8mCbAAAAA==",
  "/media/WAA_6656-HDR.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAA4BaJbACdADG7w+GDAAA/uuKCISIzy5CXrjX4NwHnE6UgWSYudHeia8eRmCqffJV6+EB8PLJhQ4qgKHDGWZ9QgQ6yPRQF/9zXuBPb1TSGl5Ub4WjDkIWJ4QA",
  "/media/WAA_6659-HDR.webp": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAQCdASoQAAsAA4BaJbACdADsIpmuIAD4Y0pkmlhMp+KzIwzHbNgdLVKUxLOVFt3rgViplh83fxhhTf4bjy9mqvUlqiazhViKn75o7LcldZnzNzYOUUJa23N9BuilOnQGiS4dHJ66xIP7QAA=",
  "/media/WAA_6667-HDR.webp": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAQCdASoQAAsAA4BaJbACdAD6luo/zmQA9fft1ttp61xG6tc4uGhFo5XTnKFMNCGx/9UNpzJYx2Zc551Oq59xsjoRQESUyWuYzUUaf/bOBLqo+95ayeEueW1YFl1qo9DtuMeMcAAAAA==",
  "/media/WAA_6670-HDR.webp": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAQCdASoQAAsAA4BaJaACdAC3XyZKYoAA+3YED1lzvTOgTgps04tNo2HUMI/9OvPNQ17W1kDErCjbUt4tNGIW+5ln2gMPLTbtY7e5389Xfx5cBJLBIrY3wNVns6aqRzN22PNFYlAAAA==",
  "/media/WAA_6673-HDR.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAsAA4BaJbAC7ACzbUQNcAD7oqnM7k6pOa65ScrVzDKFcuLok8uTR+fxPcn/ZbJuYCtNoTdHuC7VLNOfAunKM01HkD4u+zHWQz4oW64r5ntz32AAAA==",
  "/media/WAA_6676-HDR.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAQCdASoQAAsAA4BaJagAAfMZbzfeAP1QPeB0RE21xWQS32rTp7E9psmkQxLvHyyIGAWVmSInkCPIHLjaDK+5xUZ6evz5jt73Plu0gGwcqvccEMeZvAAA",
  "/media/WAA_6679-HDR.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAA4BaJbACdADHLHXsIgAA/sJ3UIVuxnP7wsnCYDoAj1splyuMt8M0dxhrAuojyASWofz65b/qPAX2/BAKy6HQ9fUol7DL4JCOXCSxJh5aOwOugAAA",
  "/media/WAA_6682-HDR.webp": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAsAA4BaJbACdAEfQQ0qCwBEMAD+sjrXuRAH97vwKH/vNLphM9YQNplmncvdMzva+RyF5LyijgeKgESZ6i/fVCGr+GmIAxX9mB3Dw5kRv8RKAAA=",
  "/media/WAA_6685-HDR.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAsAA4BaJbAC7AED94bMQIbnmADbgGfWl4CmadQ6BspyTrr/SSQr5LdKi/h76A0hWmk/mNriPOvoWsZR/Qh7qZGViULeteoSAAAA",
  "/media/WAA_6691-HDR.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJYgCdAEfVu8n81B5YAD88mPUmm2XTjzvXen92xXmr0LLtfUD4MxptLpV7bk1SiIJ+H9MvhaHLhem5KCSht2WiiQa+yEcIAWuCCGBN6AAAA==",
  "/media/WAA_6694-HDR.webp": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAA4BaJbACdADY5BH+WADhsoUCO4oNcWOX4rY0zfc2zG55TaVqsFIC3LN/Uyic7+NrPfD7xsXuP2ynuwAdZn5BpVq6j/D4FzF+MCxBPXb6QAA=",
  "/media/WAA_6700-HDR.webp": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAA4BaJbACdBXgBKKFIUbnTAAA9nwcEc5rdrX1mYqYM55d6s/cFSvfwqqvdPKgDBZQjD4FuJmp29GcDZWSXKluq9ZXZSBKnxkWwmT+z2AMwUNjqYDekuQAAA==",
  "/media/WAA_6703-HDR.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJbACdADOpYNOw3gAAP7XmExHWAwS/BxJpa7VT7/MCiBfH+AlKTlVyqdwUhdUfpcAaBRHmDSryy7RdBfZN+DAHSOKIiBgB3hz4wEz3GHS8YBfuse3fgAA",
  "/media/WAA_6706-HDR.webp": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsAA4BaJbACdAD6d1u+B4G0AADiXUv8nxDsmLG4R/c42KwfY9agiN6BSYULVfBgz8QP6JCKvq+vgbEOHy7q6sqsx2QgPgd1Q3Gf637i/0BLn16ra0EMgAAAAA=="
};
export const getBlur = (src: string) => {
  const key = src.replace(/^.*?(?=\/media\/)/, '');
  return blurData[key];
};
