// Optimizes media-src/**/*.JPG → public/media/**/*.webp + lib/blurData.ts
// Usage: npm run optimize:media
import sharp from 'sharp';
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(root, '..', 'media-src');
const OUT = path.join(root, '..', 'public', 'media');
const BLUR_FILE = path.join(root, '..', 'lib', 'blurData.ts');

const isPano = (name) => /pano/i.test(name);

async function* walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else if (/\.jpe?g$/i.test(e.name)) yield p;
  }
}

const blurMap = {};
let srcBytes = 0;
let outBytes = 0;

for await (const file of walk(SRC)) {
  const rel = path.relative(SRC, file); // e.g. "night/DSC00098-HDR-Pano.JPG"
  const relWebp = rel.replace(/\.jpe?g$/i, '.webp');
  const outPath = path.join(OUT, relWebp);
  await mkdir(path.dirname(outPath), { recursive: true });

  const img = sharp(file);
  const meta = await img.metadata();
  srcBytes += (await import('node:fs')).statSync(file).size;

  const maxW = isPano(rel) ? 4096 : 1920;
  const q = isPano(rel) ? 75 : 78;
  const resized = meta.width > maxW ? img.resize({ width: maxW }) : img;
  await resized.webp({ quality: q }).toFile(outPath);

  const stat = await import('node:fs').then((fs) => fs.statSync(outPath));
  outBytes += stat.size;

  // Tiny blur placeholder
  const blur = await sharp(file)
    .resize({ width: 16 })
    .webp({ quality: 40 })
    .toBuffer();
  blurMap[`/media/${relWebp.replaceAll(path.sep, '/')}`] =
    `data:image/webp;base64,${blur.toString('base64')}`;

  console.log(`${rel} → ${relWebp} (${(stat.size / 1024).toFixed(0)} KB)`);
}

const ts = `// GENERATED by scripts/optimize-media.mjs — do not edit by hand.
// Tiny blur placeholders (16px WebP, base64) keyed by public path.
export const blurData: Record<string, string> = ${JSON.stringify(blurMap, null, 2)};
export const getBlur = (src: string) => {
  const key = src.replace(/^.*?(?=\\/media\\/)/, '');
  return blurData[key];
};
`;
await writeFile(BLUR_FILE, ts);

console.log(`\nTotal: ${(srcBytes / 1048576).toFixed(1)} MB → ${(outBytes / 1048576).toFixed(1)} MB`);
console.log(`Blur map → ${path.relative(root, BLUR_FILE)} (${Object.keys(blurMap).length} entries)`);
